CREATE TABLE IF NOT EXISTS todos (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  description TEXT,
  done BOOLEAN NOT NULL DEFAULT 'f',
  published BOOLEAN NOT NULL DEFAULT 'f'
);